### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by larshesel** [benoitc/rebar3_protobuffs#1]
Hi @benoitc 

I was delighted to see that you've build a rebar3 protobuffs provider, thanks!

I did run into an issue which seems to be related to the protobuffs dependency `{protobuffs, "0.8.2"}`. I've added the provider to my rebar.config like this:

``` erlang
 {plugins, [rebar3_protobuffs]}.
```

And if I try to fetch and compile it according to the rebar3 docs (https://www.rebar3.org/docs/plugins#section-using-a-plugin) I get this:

``` bash
$ rebar3 rebar3_protobuffs
===> Fetching rebar3_protobuffs ({git,
                                         "git://github.com/benoitc/rebar3_protobuffs.git",
                                         {tag,"0.2.0"}})
===> Fetching protobuffs ({pkg,<<"protobuffs">>,<<"0.8.2">>})
===> Insecure HTTPS request (peer verification disabled), please update to OTP 17.4 or later
===> Version cached at /home/lhc/.cache/rebar3/hex/default/packages/protobuffs-0.8.2.tar is up to date, reusing it
===> Fetching meck ({pkg,<<"meck">>,<<"0.8.3">>})
===> Insecure HTTPS request (peer verification disabled), please update to OTP 17.4 or later
===> Version cached at /home/lhc/.cache/rebar3/hex/default/packages/meck-0.8.3.tar is up to date, reusing it
===> Compiling meck
===> Compiling protobuffs
===> Compiling /home/lhc/dev/upptalk/dev_env/userservice/_build/default/plugins/protobuffs/src/protobuffs_scanner.erl failed
/usr/local/Cellar/erlang/18.1/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl:47: attribute 'dialyzer' after function definitions
/usr/local/Cellar/erlang/18.1/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl:118: attribute 'dialyzer' after function definitions
/usr/local/Cellar/erlang/18.1/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl:194: attribute 'dialyzer' after function definitions
/usr/local/Cellar/erlang/18.1/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl:247: attribute 'dialyzer' after function definitions

===> Plugin {rebar3_protobuffs,
                       {git,"git://github.com/benoitc/rebar3_protobuffs.git",
                           {tag,"0.2.0"}}} not available. It will not be used.
===> Command rebar3_protobuffs not found
```

Note, this is the first time I'm getting my feet wet with rebar3, so I may of course have misunderstood something ;)

As extra info I'm running rebar3 master from yesterday: https://github.com/rebar/rebar3/commit/21ae3145dfd9f24af9df962fcbf00fdb55d9b923

**Comment by benoitc** [comment]
did you do a rebar3 update ? i will check when i'm back from the swimming
pool?

**Comment by larshesel** [comment]
I hadn't done a rebar3 update recently, but it didn't solve the problem.

What I was trying to do was to upgrade a project running R16B03-1 to user rebar3, (rebar3 was compiled with erlang 18, though) and it was when I was using R16B I go the above errors and they disappear if I switch to erlang 18. I guess protobuffs is just not R16B compatible. The output I get now is:

``` bash
$ rebar3 rebar3_protobuffs
===> Fetching rebar3_protobuffs ({pkg,<<"rebar3_protobuffs">>,
                                         <<"0.2.0">>})
===> Version cached at /home/lhc/.cache/rebar3/hex/default/packages/rebar3_protobuffs-0.2.0.tar is up to date, reusing it
===> Fetching protobuffs ({pkg,<<"protobuffs">>,<<"0.8.2">>})
===> Version cached at /home/lhc/.cache/rebar3/hex/default/packages/protobuffs-0.8.2.tar is up to date, reusing it
===> Fetching meck ({pkg,<<"meck">>,<<"0.8.3">>})
===> Version cached at /home/lhc/.cache/rebar3/hex/default/packages/meck-0.8.3.tar is up to date, reusing it
===> Compiling meck
===> Compiling protobuffs
===> Compiling rebar3_protobuffs
===> Command rebar3_protobuffs not found
```

I'll try and see if I can figure out what makes it not work with R16B, but I'll assume it's not a priority for you to support such old erlang versions, so I'll close this issue.

Thanks for the help!

**Comment by benoitc** [comment]
hrm in fact it's a compiler option. Look at the readme on how to use it. You don't need to run rebar3 rebar3_protobuffs:

https://github.com/benoitc/rebar3_protobuffs#usage
